import fs from 'node:fs/promises';
import path from 'node:path';
import {transformSync} from '@babel/core';
import postcss from 'postcss';
import tailwind from 'tailwindcss';
const root=process.cwd(), output=root;
for(const file of ['__qa.html','__qa-app.html','__qa-app.js','__qa-fixture.js']) await fs.unlink(path.join(output,file)).catch(e=>{if(e.code!=='ENOENT')throw e;});
let html=await fs.readFile('app-source.html','utf8');
const sourceHtml=html;
const jsx=await fs.readFile('collaboration-source.jsx','utf8');
const compile=source=>transformSync(source,{presets:[['@babel/preset-env',{targets:{safari:'14',chrome:'90'},modules:false}],['@babel/preset-react',{runtime:'classic'}]],comments:false,compact:false}).code;
await fs.writeFile(path.join(output,'collaboration.js'),compile(jsx));
const scripts=[...html.matchAll(/<script type="text\/babel">([\s\S]*?)<\/script>/g)];
if(scripts.length!==1)throw new Error('Expected one main React script');
await fs.writeFile(path.join(output,'app.js'),compile(scripts[0][1]));
html=html.replace(scripts[0][0],'<script src="./app.js?v=3.1.0"></script>');
html=html.replace(/<script type="text\/babel" src="\.\/collaboration.jsx\?v=3.1.0"><\/script>/,'<script src="./collaboration.js?v=3.1.0"></script>');
const configMatch=html.match(/<script>\s*tailwind.config = ([\s\S]*?)\n    <\/script>/);
if(!configMatch)throw new Error('Tailwind config not found');
const config=Function('return ('+configMatch[1].trim().replace(/;$/,'')+')')();
config.content=[{raw:sourceHtml,extension:'html'},{raw:jsx,extension:'jsx'}];
// All subject and theme utility strings remain statically present in source.
const css=await postcss([tailwind(config)]).process('@tailwind base;@tailwind components;@tailwind utilities;',{from:undefined});
await fs.writeFile(path.join(output,'tailwind.css'),css.css);
html=html.replace(configMatch[0],'').replace(/<script src="https:\/\/cdn.tailwindcss.com"><\/script>/,'<link rel="stylesheet" href="./vendor/tailwind.css?v=3.1.0">');
html=html.replace(/<script src="https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/babel-standalone[^<]*<\/script>/,'');
html=html.replace(/https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/react\/18.2.0\/umd\/react.production.min.js/,'./vendor/react.js').replace(/https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/react-dom\/18.2.0\/umd\/react-dom.production.min.js/,'./vendor/react-dom.js').replace(/https:\/\/unpkg.com\/lucide@latest/,'./vendor/lucide.js');
for(const [from,to] of [['node_modules/react/umd/react.production.min.js','react.js'],['node_modules/react-dom/umd/react-dom.production.min.js','react-dom.js'],['node_modules/lucide/dist/umd/lucide.min.js','lucide.js'],['node_modules/qrcode-generator/qrcode.js','qrcode.js']])await fs.copyFile(from,path.join(output,to));
html=html.replaceAll('./vendor/','./').replaceAll('./functions/core.js','./core.js');
await fs.writeFile(path.join(output,'index.html'),html);
console.log('StudyOS 3.1.0 built: local React, icons, QR and compiled CSS/JS. Firebase SDK remains online.');
